ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tenantId" TEXT NOT NULL DEFAULT 'default';

ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "tenantId" TEXT NOT NULL DEFAULT 'default';
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "closedReason" TEXT;
ALTER TABLE "Conversation" ADD COLUMN IF NOT EXISTS "slaDueAt" TIMESTAMP(3);

ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "modelTraceId" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "promptVersion" TEXT;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "tokenUsage" INTEGER;
ALTER TABLE "Message" ADD COLUMN IF NOT EXISTS "latencyMs" INTEGER;

ALTER TABLE "Knowledge" ADD COLUMN IF NOT EXISTS "sourceFile" TEXT;
ALTER TABLE "Knowledge" ADD COLUMN IF NOT EXISTS "approvedBy" TEXT;
ALTER TABLE "Knowledge" ADD COLUMN IF NOT EXISTS "parseStatus" TEXT NOT NULL DEFAULT 'queued';
ALTER TABLE "Knowledge" ADD COLUMN IF NOT EXISTS "chunkCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "PromptTemplate" ADD COLUMN IF NOT EXISTS "approvedBy" TEXT;
ALTER TABLE "PromptTemplate" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);

ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "requestId" TEXT;
ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "beforeState" JSONB;
ALTER TABLE "AuditEvent" ADD COLUMN IF NOT EXISTS "afterState" JSONB;
